window.WEDDING_GUESTS = Object.freeze({
  "mr-rogers-mwesigye": "Mr. Rogers Mwesigye",
  "miss-florence-agwang": "Miss Florence Agwang",
  "mr-mwanda-timothy": "Mr. Mwanda Timothy",
  "miss-phiona-namuwonge": "Miss Phiona Namuwonge",
  "mr-ewoku-samuel": "Mr. Ewoku Samuel",
  "miss-claudia-grabler": "Miss Claudia Grabler",
  "mr-solomon-mugisha": "Mr. Solomon Mugisha",
  "miss-nilla": "Miss Nilla",
  "mr-francis-wenyungi": "Mr. Francis Wenyungi",
  "mr-aloyius-tumwekwase-gonzaga": "Mr. Aloysius Tumwekwase Gonzaga",
  "miss-leah-alupo": "Miss Leah Alupo",
  "mr-steven-okiror": "Mr. Steven Okiror",
  "miss-elizabeth-agwang": "Miss Elizabeth Agwang",
  "mr-and-mrs-eladu-simon": "Mr. and Mrs. Eladu Simon",
  "miss-annet-achom": "Miss Annet Achom",
  "mr-and-mrs-ssempira-paul": "Mr. and Mrs. Ssempira Paul",
  "mr-ernest-kabahima": "Mr. Ernest Kabahima",
  "mr-and-mrs-malinga-calvin": "Mr. and Mrs. Malinga Calvin",
  "mr-tom-amute": "Mr. Tom Amute",
  "mr-and-mrs-edait-pascal": "Mr. and Mrs. Edait Pascal",
  "miss-katherine-kamedde": "Katherine Kamedde",
  "aunty-florence": "Aunty Florence",
  "mr-and-mrs-munene": "Mr. and Mrs. Munene",
  "aunty-martha-pedun": "Aunty Martha Pedun",
  "mr-and-mrs-oliba-ben-paul": "Mr. and Mrs. Oliba Ben Paul",
  "miss-josephine-atim": "Miss Josephine Atim",
  "madam-do": "Madam Do",
  "miss-essie-ikedit": "Miss Essie Ikedit",
  "miss-polline-nsabiyunva": "Miss Polline Nsabiyunva",
  "mr-and-mrs-kabali": "Mr. and Mrs. Kabali",
  "mr-and-mrs-ademun-john-stephen": "Mr. and Mrs. Ademun John Stephen",
  "aunty-jomen": "Aunty Jomen",
  "mr-and-mrs-sam-osenyi": "Mr. and Mrs. Sam Osenyi",
  "mr-and-mrs-edison-amou": "Mr. and Mrs. Edison Amou",
  "mr-joshua-okanya": "Mr. Joshua Okanya",
  "mr-and-mrs-ademun-patrick": "Mr. and Mrs. Ademun Patrick",
  "miss-gloria-abbo": "Miss Gloria Abbo",
  "miss-annet-ochan": "Miss Annet Ochan",
  "miss-pamela-akwap": "Miss Pamela Akwap",
  "mr-sadiq": "Mr. Sadiq",
  "mr-kenneth-anoku": "Mr. Kenneth Anoku",
  "mr-joseph-adiama": "Mr. Joseph Adiama",
  "mr-joel-wabire": "Mr. Joel Wabire",
  "mr-japhet-mwine": "Mr. Japhet Mwine",
  "mr-and-mrs-habumugisha-joel": "Mr. and Mrs. Habumugisha Joel",
  "miss-felistus": "Miss Felistus",
  "mr-jonathan-okali": "Mr. Jonathan Okali",
  "mr-and-mrs-batekereza-daniel": "Mr. and Mrs. Batekereza Daniel",
  "mr-and-mrs-curhbert-john-agolor": "Mr. and Mrs. Curhbert John Agolor",
  "mr-and-mrs-paul-agulet": "Mr. and Mrs. Paul Agulet",
  "mr-and-mrs-benard-magogo": "Mr. and Mrs. Benard Magogo",
  "mr-and-mrs-kabali-paul": "Mr. and Mrs. Kabali Paul",
  "mr-and-mrs-richard": "Mr. and Mrs. Richard",
  "mr-and-mrs-tunezerwe": "Mr. and Mrs. Tunezerwe",
  "mr-and-mrs-opule-emmanuel": "Mr. and Mrs. Opule Emmanuel",
  "mr-and-mrs-mumbya-moses": "Mr. and Mrs. Mumbya Moses",
  "mr-ekalu-glenn-jonathan": "Mr. Ekalu Glenn Jonathan",
  "mr-and-mrs-king": "Mr. and Mrs. King",
  "mr-and-mrs-oliba-david": "Mr. and Mrs. Oliba David",
  "mr-and-mrs-edait-james": "Mr. and Mrs. Edait James",
  "agalo-joyce": "Agalo Joyce",
  "miss-atukei-racheal": "Miss Atukei Racheal",
  "mr-and-mrs-okurut-george-william": "Mr. and Mrs. Okurut George William",
  "miss-julliet-ikilai": "Miss Julliet Ikilai",
  "mr-and-mrs-muwanika-nelson": "Mr. and Mrs. Muwanika Nelson",
  "miss-beatrice-apio": "Miss Beatrice Apio",
  "mr-and-mrs-okello-kelly": "Mr. and Mrs. Okello Kelly",
  "emmy-okurut": "Emmy Okurut",
  "mr-ongodia-andrew": "Mr. Ongodia Andrew",
  "aisu-emmy": "Aisu Emmy",
  "auntie-grace": "Auntie Grace",
  "miss-anna-acio": "Miss Anna Acio",
  "miss-loy-awio": "Miss Loy Awio",
  "miss-enid": "Miss Enid",
  "o-b": "O.B",
  "mr-alvin-mainga": "Mr. Alvin Malinga",
  "mr-and-mrs-opio-wallence": "Mr. and Mrs. Opio Wallence",
  "miss-leah": "Miss Leah",
  "mr-and-mrs-oliba-richard": "Mr. and Mrs. Oliba Richard",
  "miss-adeke-caroline": "Miss Adeke Caroline",
  "miss-susan-okedi": "Miss Susan Okedi",
  "mr-amos": "Mr. Amos",
  "mr-and-mrs-idiamat-martin": "Mr. and Mrs. Idiamat Martin",
  "miss-zipporah": "Miss Zipporah",
  "anna-kalumuna": "Anna Kalumuna",
  "mr-and-mrs-omiat-david": "Mr. and Mrs. Omiat David",
  "emma-opio": "Emma Opio",
  "scovia-katushabe": "Scovia Katushabe",
  "alimo-anneros": "Alimo AnneRose",
  "clever-r": "Clever R.",
  "vicky": "Vicky",
  "john-rich": "John Rich",
  "samuel-njuki": "Samuel Njuki",
  "joshua-s-aka-uncle-pizza": "Joshua S. AKA Uncle Pizza",
  "miss-suzan-acom": "Miss Suzan Acom",
  "samson-sammy-danielz": "Samson Sammy Danielz",
  "ivan": "Ivan",
  "aine-praise": "Aine Praise",
  "mr-akora-solomon": "Mr. Akora Solomon",
  "anthony-kweya": "Anthony Kweya",
  "azandu-owen-r": "Azandu Owen R",
  "mr-bahinda-solomon": "Mr. Bahinda Solomon",
  "bidha-brian": "Bidha Brian",
  "biira-zeresi": "Biira Zeresi",
  "blessing-ayebale": "Blessing Ayebale",
  "david-kajoba": "David Kajoba",
  "mr-emon-matovu": "Mr. Emon Matovu",
  "favour-kiiza": "Favour Kiiza",
  "bogere-moses": "Bogere Moses",
  "miss-gorret-ayesiga": "Miss Gorret Ayesiga",
  "hilarry": "Hilarry",
  "isiiko-ivan": "Isiiko Ivan",
  "mr-tumusiime-ezra": "Mr. Tumusiime Ezra",
  "joshua-kayongo": "Joshua Kayongo",
  "kasozi-david": "Kasozi David",
  "kisitu-samuel": "Kisitu Samuel",
  "mugambwa-joel": "Mugambwa Joel",
  "mutungi-ambrozio": "Mutungi Ambrozio",
  "mwegyesa-jessy": "Mwegyesa Jessy",
  "mwenkanya-reynold": "Mwenkanya Reynold",
  "mr-probuse-nimukama": "Mr. Probuse Nimukama",
  "rose-jacent": "Rose Jacent",
  "sam-nturanabo": "Sam Nturanabo",
  "miss-sarah-galiwango": "Miss Sarah Galiwango",
  "shamim-nakayiza": "Shamim Nakayiza",
  "simbulireki-wingard": "Simbulireki Wingard",
  "steven-mpawulo": "Steven Mpawulo",
  "mr-denise-kimanya": "Mr. Denis Kimanya",
  "miss-christine-kankunda": "Miss Christine Kankunda",
  "mr-andrew-muhereza": "Mr. Andrew Muhereza",
  "mr-elvis-mukanuka": "Mr. Elvis Mukanuka",
  "mr-ivan-muhwezi": "Mr. Ivan Muhwezi",
  "mr-apollo-ashaba": "Mr. Apollo Ashaba",
  "mrs-lisa-natuhwera": "Mrs. Lisa Natuhwera",
  "mrs-annet-n": "Mrs. Annet N",
  "mr-paddy-kabanda": "Mr. Paddy Kabanda",
  "derrick": "Derrick",
  "mr-rutsobe-brian": "Mr. Rutsobe Brian",
  "ms-ann-mary-kusiima": "Ms. Ann Mary Kusiima",
  "mr-and-mrs-sebana-joseph": "Mr. and Mrs. Sebana Joseph",
  "ms-ann-mary-kusiima-2": "Ms. Ann Mary Kusiima",
  "ms-phoebe-nabunya": "Ms. Phoebe Nabunya",
  "ann-mary-kusiima": "Ann Mary Kusiima",
  "ssegayi-farouk": "Ssegayi Farouk",
  "mrs-james-kamanya": "Mrs. James Kamanya",
  "mummy-rose": "Mummy Rose",
  "miss-lydia-nabakooza": "Miss Lydia Nabakooza",
  "mr-mark-muwonge": "Mr. Mark Muwonge",
  "miss-sophie-muwumuza": "Miss Sophie Muwumuza",
  "miss-cossy-ntongo": "Miss Cossy Ntongo",
  "mr-dickens-amanya": "Mr. Dickens Amanya",
  "mr-and-mrs-jimmy-kiwumulo": "Mr. and Mrs. Jimmy Kiwumulo",
  "mr-and-mrs-richard-ayesigwa": "Mr. and Mrs. Richard Ayesigwa",
  "miss-ameso-stella": "Miss Ameso Stella",
  "miss-alex-sewali": "Miss Alex Sewali",
  "mr-francis-kagolo": "Mr. Francis Kagolo",
  "daddy-majwala-and-family": "Daddy Majwala and family",
  "miss-sheila-nalukwago": "Miss Sheila Nalukwago",
  "mrs-kyaligonza-doreen": "Mrs. Kyaligonza Doreen",
  "mr-and-mrs-semei-nyanzi": "Mr. and Mrs. Semei Nyanzi",
  "mr-luswata-tonny": "Mr. Luswata Tonny",
  "mr-lule-francis": "Mr. Lule Francis",
  "miss-namayanja-stella": "Miss. Namayanja Stella",
  "mr-sseremba-andrew": "Mr. Sseremba Andrew",
  "mr-majwala-edward": "Mr. Majwala Edward",
  "mr-nabulomi-walter": "Mr. Nabulomi Walter",
  "miss-kayana-ruth": "Miss Kayana Ruth",
  "mr-leju-charles": "Mr. Leju Charles",
  "dev-sham": "Dev Sham",
  "pastor-jimmy": "Pastor Jimmy",
  "mr-&-mrs.-wabweyo": "Mr. & Mrs. Wabweyo",
  "mr-&-mrs.-mutete": "Mr. & Mrs. Mutete",
  "mr-&-mrs.-ssekanza": "Mr. & Mrs. Ssekanza",
  "mr-&-mrs.-othieno": "Mr. & Mrs. Othieno",
  "mr-&-mrs.-ziraba": "Mr. & Mrs. Ziraba",
  "mr-&-mrs.-kalumuna": "Mr. & Mrs. Kalumuna",
  "mr-&-mrs.-okipi": "Mr. & Mrs. Okipi",
  "mr-&-mrs.-otim": "Mr. & Mrs. Otim",
  "mr-&-mrs.-lwaze": "Mr. & Mrs. Lwaze",
  "mr-&-mrs.-joshua-ssekyanzi": "Mr. & Mrs. Joshua Ssekyanzi",
  "mr-&-mrs.-bugingo": "Mr. & Mrs. Bugingo",
  "mr-&-mrs.-njuki": "Mr. & Mrs. Njuki",
  "mr-&-mrs.-angoyar-opio": "Mr. & Mrs. Angoyar Opio",
  "miss-brenda-abibi": "Miss. Brenda Abibi",
  "mr-marvin-odongo": "Mr. Marvin Odongo",
  "mr-samson-rwetwara": "Mr. Samson Rwetwara",
  "ms-cynthia-d.-naluswata": "Ms. Cynthia D. Naluswata",
  "ps-sande-waiswa-william": "Ps. Sande Waiswa William",
  "ms-mary-maleng": "Ms. Mary Maleng",
  "dr-kosmas-malinga": "Dr. Kosmas Malinga",
  "mr-laban-biryabarema": "Mr. Laban Biryabarema",
  "mr-joseph-olupot": "Mr. Joseph Olupot",
  "ms-suzan-acom": "Ms. Suzan Acom",
  "mr-anne-rose-alimo": "Mr. Anne Rose Alimo",
  "ms-scovia-katushabe": "Ms Scovia Katushabe",
  "mr-clever-rwigyema": "Mr. Clever Rwigyema",
  "ms-dorothy-amongin": "Ms. Dorothy Amongin",
  "ms-jackline-akoli": "Ms. Jackline Akoli",
  "mr-timothy-wanyama": "Mr. Timothy Wanyama",
  "dr-william-m.-waibi": "Dr. William m. Waibi",
  "ms-shakira-nyamwiza": "Ms Shakira Nyamwiza",
  "mr-alex-mumbya": "Mr. Alex Mumbya",
  "ms-allen-takoba": "Ms. Allen Takoba",
  "mr-paul-geraldson-mugaya": "Mr. Paul Geraldson Mugaya",
  "ms-josphine-salma": "Ms. Josphine Salma",
  "ms-ephrance-guttabingi-lwanga": "Ms. Ephrance Guttabingi Lwanga",
  "mr-justine-absolom-otim": "Mr. Justine Absolom Otim",
  "ms-patience-rinnah-okide": "Ms. Patience Rinnah Okide",
  "ms-florence-namukasa": "Ms. Florence Namukasa",
  "mr-&-mrs.-habumugisha-robert": "Mr. & Mrs. Habumugisha Robert",
  "pastor-dora-wataba": "Pastor Dora Wataba",
  "pastor-richard": "Pastor Richard",
  "mr-kakooza-john-bosco": "Mr. Kakooza John Bosco",
  
});
